"Filed out from Dolphin Smalltalk 7"!

SmalltalkParser subclass: #SSWSmalltalkSpyParser
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	classInstanceVariableNames: ''!
SSWSmalltalkSpyParser guid: (GUID fromString: '{90039803-3670-11d6-87e5-0010a70883e2}')!
SSWSmalltalkSpyParser comment: ''!
!SSWSmalltalkSpyParser categoriesForClass!Unclassified! !
!SSWSmalltalkSpyParser methodsFor!

methodNodeClass

	"The receiver class exists only to allow Spied Methods to specify their own method node class"

	^SSWSpyMethodNode! !
!SSWSmalltalkSpyParser categoriesFor: #methodNodeClass!constants!public! !

